/* ROOT_DEEP — the "Learn more" deep-study layer for the Drill Hall Roots focus.
   Keyed by the exact root form used in the gates (and mirroring the ETYM keys),
   plus the individual pieces that "A + B" compound roots split into, so every
   drilled root resolves to a richer note. Each entry expands the terse ETYM line
   into a fuller reading: the root's origin and literal sense, how that sense
   developed, and a vivid English descendant to anchor it. Where an entry is
   missing, the panel falls back to the one-line ETYM note, so nothing is ever
   blank. Voice follows the app's ETYM/DEPTH register: literate, concrete, brief.
   Rendered as HTML — keep values free of < > &, and use single quotes inside. */
window.ROOT_DEEP = {
"ego":"Latin for 'I' — simply the word a Roman used to point at himself, the plainest pronoun there is. It kept that ordinary sense for centuries until Freud drafted it into psychology as the conscious, deciding self that referees between appetite and conscience; an egoist keeps the reward, an egotist keeps talking about himself.",
"alter":"Latin for 'the other of two' — not a vague other, but the specific second party in a pair. From that pairing English drew alternate (first one, then the other), alter ego (a second self), and, by way of 'concern for the other,' altruism; an altercation is a quarrel driven back and forth between the two.",
"verto / versus":"Latin vertere, 'to turn,' with its past participle versus, 'turned' — a single pivoting motion. That turn fans out across English into convert (turn around), reverse (turn back), divert (turn aside), and version (the particular turn a story takes); versus survives wherever two sides are turned against each other.",
"intro-":"Latin intro, 'to the inside' — an adverb pointing the action inward. Bolted onto a verb it aims within: the introvert turns inward, an introduction leads you into a subject. It is the quiet mirror of extra-.",
"extra-":"Latin extra, 'outside, beyond' — past the edge of the usual. It marks the extrovert who turns outward, the extraordinary that steps beyond the ordinary, and the external that lies outside; where intro- retreats, extra- always reaches past the boundary.",
"ambi-":"Latin ambi-, 'both' or 'around' — taking in two sides at once. The ambidextrous treat both hands as the right, the ambivalent are pulled both ways at heart, the ambiguous point in two directions of meaning; its Greek cousin is amphi-.",
"misein":"Greek misein, 'to hate' — active, chosen loathing, not mere dislike. It supplies the mis- of misanthrope, the hater of mankind, and misogyny, hatred of women; wherever it appears, someone is being turned against on principle.",
"anthropos":"Greek anthropos, 'human being' — humankind as a species, not one man. Anthropology takes it as its subject and philanthropy loves it, while the misanthrope has given up on it entirely.",
"asketes":"Greek asketes, 'one who trains,' from askein, 'to exercise' — first an athlete drilling the body. The word crossed into the spiritual gym of the desert monks, and the ascetic now disciplines appetite the way a runner once disciplined muscle.",
"internus":"Latin internus, 'inward,' built on inter, 'between' — what lies within the walls. From it come internal affairs and the internist, the physician of the body's inner workings rather than its surface.",
"obstetrix":"Latin obstetrix, 'one who stands before,' from ob- (before) plus stare (to stand) — the midwife who stood ready to receive the child. Obstetrics still names the medicine of that waiting moment at birth.",
"pais, paidos":"Greek pais, 'child' (stem paid-) — the young one under instruction. It gives the ped- of pediatrics, the medicine of children, and the -pedia of encyclopedia, an all-round 'education of the child.'",
"derma":"Greek derma, 'skin' — the body's outer hide. Dermatology treats it and the epidermis is the layer laid 'upon' it; a pachyderm is simply a thick-skinned beast.",
"ophthalmos":"Greek ophthalmos, 'eye' — the organ of sight itself. The ophthalmologist, whose tongue-twisting name keeps the full Greek, is its physician.",
"orthos":"Greek orthos, 'straight, correct' — upright in both the literal and the moral sense. Orthodox belief is the straight opinion, orthopedics once aimed to straighten the child's crooked bones, and orthography is correct spelling.",
"kardia":"Greek kardia, 'heart' — the beating organ, and by old habit the seat of courage. Cardiac arrest and cardiology carry it into the clinic.",
"neuron":"Greek neuron, 'sinew, cord' — originally the body's tough fibres, later narrowed to the nerve. Neurology studies the network, and the neuron is its single signalling cell.",
"psyche":"Greek psyche, 'breath, soul' — the life that leaves on the last exhalation, later personified as a maiden loved by Eros. Psychology is the study of that inner life, and the psyche is its whole animating self.",
"iatreia":"Greek iatreia, 'healing,' from iatros, 'physician' — the doctor's craft. It survives as the -iatry of psychiatry, the healing of the mind, and podiatry, the healing of the feet.",
"odontos":"Greek odous, 'tooth' (stem odont-) — the biting edge. The orthodontist straightens teeth, and the mastodon was named for the nipple-shaped cusps on its own.",
"opsis / optikos":"Greek roots of sight — opsis, 'a seeing,' and optikos, 'of vision.' They give the optic nerve, optometry (measuring sight), and autopsy, literally 'a seeing for oneself.'",
"metron":"Greek metron, 'measure' — the standard against which a thing is gauged. It stands behind the metre, the thermometer that measures heat, and geometry, the old measuring of the earth.",
"osteon":"Greek osteon, 'bone' — the body's frame. The osteopath treats it, and osteoporosis is the bone gone porous with age.",
"cheir":"Greek cheir, 'hand' — the working hand. The chiropractor heals by hand, and surgery itself is 'hand-work' hidden inside the Greek cheirourgia.",
"pous, podos":"Greek pous, 'foot' (stem pod-) — the base a body stands on. It walks through podiatry, the three-footed tripod, and the octopus, the 'eight-foot.'",
"graphein":"Greek graphein, 'to scratch, write' — first the stylus cut into wax. From that scratch come the graph, biography (a life written down), and photograph (writing with light).",
"geron":"Greek geron, 'old man' — age itself. Gerontology studies it and geriatric medicine tends it.",
"analyein":"Greek analyein, 'to loosen up,' ana- (up) plus lyein (to loosen) — to untie a knot. Analysis still means loosening a whole into its threads to see how it was tied.",
"astron":"Greek astron, 'star' — a point of the night sky. Astronomy charts the stars, the astronaut sails among them, and disaster is, at root, a ruinous 'bad star.'",
"nomos":"Greek nomos, 'law, custom,' from nemein, 'to distribute' — the apportioning that becomes rule. It is the -nomy of astronomy, the ordering of the stars, and economy, the law of the household.",
"ge":"Greek ge, 'earth,' worshipped as the goddess Gaia — the ground under everything. It opens geography (earth-writing), geology (earth-study), and geometry (earth-measure).",
"bios":"Greek bios, 'life' — a life lived and its span. Biology studies it, biography records one, and an antibiotic works 'against life,' the life of the microbe.",
"botane":"Greek botane, 'pasture, herb,' from boskein, 'to feed' — the green fodder of grazing land. Botany grew from it into the whole science of plants.",
"zoion":"Greek zoion, 'living creature' — an animal as an animate thing. It stocks the zoo, drives zoology, and names the single-celled protozoa, the 'first animals.'",
"entomon":"Greek entomon, 'the notched one,' for the insect's segmented, cut-in body. Entomology, the study of insects, keeps that ancient close look at their nicked anatomy.",
"etymon":"Greek etymon, 'the true sense of a word' — a word's genuine, original meaning. Etymology is the search for that truth, tracing a word back to what it first meant.",
"socius":"Latin socius, 'ally, companion' — one who shares your undertaking. Society, the social, and the business associate all rest on that bond of shared enterprise.",
"logos":"Greek logos — 'word,' but also 'reason' and 'account,' speech and the thought behind it fused in one term. It ends countless -logy studies (the reasoned account of a subject) and stands alone in logic.",
"noscere / notus":"Latin noscere, 'to get to know,' with its participle notus, 'known' — coming to recognise a thing. From it: notorious (widely known, for ill), notice (a coming-to-know), and the note that fixes it in memory.",
"summa":"Latin summa, 'the highest, topmost' — the top line, where Roman clerks wrote the total. Hence the summit, the sum that totals a column, and the summary that gathers it all at the top.",
"corrigere":"Latin corrigere, com- (thoroughly) plus regere (to keep straight) — to set right. It gives correct, and the incorrigible, who cannot be straightened out at all.",
"vetus":"Latin vetus, 'old' — aged, of long standing. The veteran has grown old in service, and the inveterate habit has hardened with age into second nature.",
"genitus":"Latin genitus, past participle of gignere, 'to beget' — brought into being. Congenital traits are born with you, and the genitive case marks the source a thing sprang from.",
"chronos":"Greek chronos, 'time,' old enough to be a god — duration itself. A chronic ailment drags on in time, chronology sets events in their order, and to synchronize is to make clocks agree.",
"pathos":"Greek pathos, 'suffering, feeling' — what befalls and is felt. Pathology reads the body's suffering, sympathy feels with another, and the many -path words trace who feels what.",
"scire":"Latin scire, 'to know' — sure, settled knowledge. Science is organised knowing, conscience is knowing-with-oneself, and the prescient know a thing before it comes.",
"grex, gregis":"Latin grex, 'flock, herd' (stem greg-) — beasts gathered together. The gregarious flock to company, a congregation herds into worship, and to segregate is to cut one from the flock.",
"par":"Latin par, 'equal' — matched, on a level. It stands in par and parity, lets us compare (set side by side as equals), and, when the match is denied, disparage.",
"aequus + vox":"Latin aequus, 'equal,' joined to vox, 'voice' — to give both sides an equal voice, and so to speak on both at once. That double-tongued balancing act is equivocation.",
"placare":"Latin placare, 'to calm, appease' — to smooth a temper down. To placate is to soothe, the placid surface is unruffled, and the implacable can never be soothed at all.",
"scribere":"Latin scribere, 'to write' — to cut letters into a surface. The scribe does it for a living, to describe is to write a thing down fully, and a manuscript is written by hand.",
"via":"Latin via, 'road, way' — the Roman highway. We still travel via a place, to deviate is to stray off the road, and the obvious is what lies right in your way.",
"miles, militis":"Latin miles, 'soldier' (stem milit-) — a man under arms. The military is his profession, and the militant carries a soldier's fight into peacetime causes.",
"malus":"Latin malus, 'bad, evil' — the plain word for wrong. It sours into malice, the wish to harm, malady, a bad turn of health, and malign, to speak evil of.",
"condonare":"Latin condonare, com- (fully) plus donare (to give) — to give up a claim, to forgive a debt outright. To condone is to waive the reckoning and let an offence pass.",
"adulari":"Latin adulari, 'to fawn' — the cringing wag of a dog at its master's feet. Adulation is praise pitched at just that servile angle.",
"vacillare":"Latin vacillare, 'to sway, totter' — the unsteady rocking of something about to fall. To vacillate is to totter in the same way between two choices, never coming down.",
"tacere":"Latin tacere, 'to be silent' — to hold one's tongue. A tacit agreement is understood without a word, and the taciturn keep their silence by habit.",
"Lakonia":"Lakonia, the region of Sparta, whose soldiers were famed for cutting speech to the bone — when threatened with destruction 'if,' they are said to have answered only 'if.' From their curtness comes laconic, terse to the point of bluntness.",
"garrire":"Latin garrire, 'to chatter' — the endless small noise of talk. Garrulous describes the talker who runs on and cannot stop.",
"volvere":"Latin volvere, 'to roll, turn' — a rolling revolution. It turns up in revolve, in the volume that was once a rolled scroll, and in the voluble speaker whose words roll on without check.",
"verbum":"Latin verbum, 'word' — the spoken unit itself. It anchors the verb, the verbal, the verbatim quotation word-for-word, and the verbose who use far too many.",
"cogere":"Latin cogere, com- (together) plus agere (to drive) — to drive into one, to force. A cogent argument compels assent by that same driving-together of its points.",
"vox + ferre":"Latin vox, 'voice,' with ferre, 'to carry' — a voice that carries far and loud. The vociferous carry theirs into every room.",
"sententia":"Latin sententia, 'opinion, judgment,' from sentire, 'to feel' — a settled view. It gives the sentence, first a verdict and then a full thought, and the sententious, forever handing down weighty little judgments.",
"tergere":"Latin tergere, 'to wipe' — to wipe a surface clean. It leaves the -terge of detergent and, wiped smooth and polished, the terse phrase with nothing extra clinging to it.",
"Martinet":"From Jean Martinet, Louis XIV's drillmaster, whose parade-ground discipline was merciless — the man became the byword. A martinet is anyone who enforces the smallest rule with the same rigid zeal.",
"sykon + phainein":"Greek sykon, 'fig,' plus phainein, 'to show' — the old informer's gesture of 'showing the figs,' denouncing the smugglers of Athens' sacred fruit. From that pointing finger comes sycophant, now the flatterer who curries favour.",
"dilettare":"Italian dilettare, 'to delight,' from Latin delectare — to take pleasure. The dilettante dabbles in an art for the sheer delight of it, and only that far.",
"vir":"Latin vir, 'man, hero' — manhood in its heroic key. It stands behind virile, virtue (once the specific courage of a man), and the triumvirate, a rule of three men.",
"Chauvin":"From Nicolas Chauvin, a soldier of Napoleon whose devotion outlasted all reason — he cheered an emperor who had ruined him. Chauvinism is that blind, boastful loyalty to one's own side.",
"eikon + klaein":"Greek eikon, 'image,' plus klaein, 'to break' — a smasher of sacred images, from the Byzantine quarrels over holy icons. The iconoclast now breaks not statues but received ideas.",
"hypochondria":"Greek hypochondria, 'the soft parts below the ribs,' where old physicians located the seat of black bile and melancholy. As that gloom was blamed for imagined illness, the word slid to the sufferer forever certain he is sick.",
"ciarlare":"Italian ciarlare, 'to chatter, patter' — the fast talk of a market pitch. The charlatan is the babbling quack who sells cures by patter alone.",
"Philistine":"The Philistines, the sea-people who warred on ancient Israel, cast in scripture as the brutish enemy. Later scholars borrowed the name for anyone smugly deaf to art and ideas.",
"monos + mania":"Greek monos, 'one, single,' plus mania, 'madness' — a madness fixed on a single object. Monomania is the mind clamped to one idea and blind to all else.",
"vivere":"Latin vivere, 'to live' — life in action. It burns in the vivid, the vivacious, and the survivor who lives on 'beyond' the rest.",
"fatigare":"Latin fatigare, 'to weary, wear down' — to exhaust by effort. Fatigue is the weariness itself, and the indefatigable are the untiring who never feel it.",
"ingenuus":"Latin ingenuus, 'native, freeborn' — and so, in Roman eyes, frank and without a slave's guile. Ingenuous now means open and artless, trusting to the point of innocence.",
"magnus + animus":"Latin magnus, 'great,' with animus, 'spirit' — greatness of soul. The magnanimous carry that largeness into how they treat a beaten rival: generously, above pettiness.",
"vertere":"Latin vertere, 'to turn' — the master verb of turning. It spins off convert, versatile (able to turn to anything), and adversity, the luck that has turned against you.",
"Stoa":"The Stoa Poikile, the painted porch in Athens where Zeno taught his followers to meet fortune unmoved. From that porch the Stoic takes his name and his calm.",
"trepidus":"Latin trepidus, 'agitated, alarmed' — trembling at what may come. Trepidation is that anxious flutter, and the intrepid are the ones who feel none of it.",
"scintilla":"Latin scintilla, 'spark' — the smallest fleck of fire. To scintillate is to throw off sparks, and scintillating wit flashes with them.",
"urbs":"Latin urbs, 'city' — the walled town itself. It gives urban and suburb, and the urbane, polished to a smooth city gloss.",
"gamos":"Greek gamos, 'marriage' — the wedded bond. It counts the spouses in monogamy (one), polygamy (many), and bigamy (an unlawful second).",
"monos":"Greek monos, 'single, alone' — one and only one. It stands alone in monopoly, monologue, and the flat sameness of monotony.",
"bi-":"Latin bi-, 'two, twice' — a pair or a doubling. It rides the two-wheeled bicycle, the bilingual tongue, and the biennial event that comes every second year.",
"polys":"Greek polys, 'many' — plenty of a thing. It crowds the many-sided polygon, the polyglot who speaks many tongues, and polygamy's many spouses.",
"aner, andros":"Greek aner, 'man, male' (stem andr-) — the male specifically. It shapes the android built in a man's likeness, misandry (hatred of men), and polyandry (a woman's many husbands).",
"agora":"Greek agora, 'assembly, marketplace' — the open square where Athens gathered to trade and argue. Agoraphobia is dread of just such wide, public, exposed spaces.",
"claustrum":"Latin claustrum, 'a lock, an enclosure' — a shut-in space. It gives the cloister, walled from the world, and claustrophobia, the fear of being closed in.",
"xenos":"Greek xenos, 'stranger, guest' — the outsider who might be either. Xenophobia is fear of the stranger, and the inert gas xenon was named 'the strange one.'",
"akros":"Greek akros, 'topmost, at the tip' — the highest point. The acrobat performs up high, the acropolis crowns the city, and acrophobia is the dread of heights.",
"kleptein":"Greek kleptein, 'to steal' — the thief's own verb. Kleptomania is a compulsion to steal, and a kleptocracy is government by those who loot the state.",
"kratos / -cracy":"Greek kratos, 'strength, rule' — power to hold sway. As the ending -cracy it names who holds it: the people in democracy, the best in aristocracy.",
"archein / -archy":"Greek archein, 'to rule, to be first' — both first in time and first in power. It gives the -archy of monarchy and anarchy (rule, or its absence) and the arch- that makes an archbishop chief of bishops.",
"autos":"Greek autos, 'self' — one's own self, acting alone. It runs the automatic that moves itself, autonomy (self-rule), and the autograph written in one's own hand.",
"oligos":"Greek oligos, 'few' — a small number. An oligarchy is rule gripped by the few, and an oligopoly a market cornered by a handful.",
"ploutos":"Greek ploutos, 'wealth,' hoarded by the god Plutus of the underworld's riches. A plutocracy is rule by the rich, power that money buys.",
"theos":"Greek theos, 'god' — divinity itself. Theology reasons about it, the atheist denies it, and monotheism worships just one.",
"mater":"Latin mater, 'mother' — the bearing parent. She stands behind the maternal, the matron, the matriarchy she heads, and even the matrix, first the womb from which a thing is formed.",
"pater":"Latin pater, 'father' — the head of the Roman household. He fathers the paternal, the patriarch, and the patriot, loyal to the fatherland.",
"hieros":"Greek hieros, 'holy, sacred' — set apart for the gods. A hierarchy was first a 'rule of the sacred,' priests ranked by holiness, and hieroglyphs are 'sacred carvings.'",
"demos + agogos":"Greek demos, 'the people,' with agogos, 'leader' — one who leads the crowd. The demagogue leads it by flattery and fear rather than reason.",
"loqui / locutus":"Latin loqui, 'to speak,' with its participle locutus — talk in flow. It gives the eloquent, the loquacious who talk freely, and circumlocution, talking all the way around a point.",
"dicere / dictus":"Latin dicere, 'to say' (participle dictus) — the plain act of saying. It speaks in dictate, in the verdict (a 'true saying'), and in the contradiction that says against.",
"solus":"Latin solus, 'alone' — single and unaccompanied. It performs the solo, keeps the solitary apart, and murmurs the soliloquy, a speech made to oneself alone.",
"circum":"Latin circum, 'around' — a full turn about a centre. It draws the circle, measures the circumference, and sails the globe in circumnavigate.",
"grandis":"Latin grandis, 'full-grown, great' — grown to imposing size. It swells into the grand, the grandiose, and to aggrandize, to build a thing up larger.",
"e / ex":"Latin e-, ex-, 'out of' — motion out from within. It walks through the exit, sends out in emit, and calls forth in evoke.",
"bene":"Latin bene, 'well, good' — the adverb of good outcome. It blesses the benefit, the benevolent who wish well, and the benediction, a 'good saying' spoken over you.",
"male":"Latin male, 'badly' — the adverb of harm. It curses in malediction, wishes ill in malevolent, and breaks down in malfunction.",
"com / col":"Latin com-, 'with, together' (col- before l) — joined action. It combines, collects, and collaborates, always pulling parts into one.",
"jus, juris":"Latin jus, 'law, right' (stem jur-) — the binding rule and the right it grants. It underwrites justice, the jury, and the jurisdiction where a court's writ runs.",
"judex, judicis":"Latin judex, 'judge' — from jus, 'law,' plus dicere, 'to say': the one who speaks the law. It gives the judicial bench and prejudice, a verdict passed before the hearing.",
"lis, litis":"Latin lis, 'lawsuit, dispute' (stem lit-) — a quarrel taken to court. To litigate is to fight it there, and the litigious go looking for the fight.",
"jurare":"Latin jurare, 'to swear an oath' — to bind oneself by sacred word. It seats the jury, sworn to a true verdict; perjury breaks the oath, and to abjure is to swear a thing away.",
"verus":"Latin verus, 'true' — matching the fact. It lets us verify, hand down a verdict (a 'true saying'), and speak of veracity, plain truthfulness.",
"culpa":"Latin culpa, 'fault, blame' — the guilt that attaches to a wrong. It marks the culprit and the culpable, while to exculpate is to clear the blame away.",
"crimen":"Latin crimen, 'charge, accusation' — first the indictment, then the deed itself. It names the crime, and to incriminate is to fasten the charge onto someone.",
"prudentia":"Latin prudentia, worn down from providentia, 'foresight' — seeing trouble before it lands. The prudent act on that foresight, and jurisprudence is the seasoned wisdom of the law.",
"dikē":"Greek dike, 'justice, right' — the order a case ought to reach. It survives in the -dicy of theodicy, the attempt to square a just God with the world's evil.",
"in-":"Latin in-, doing double duty: 'in, into, against' in invade and incur, but also a flat 'not' in invalid and inept. Context decides whether it drives inward or simply negates.",
"tele-":"Greek tele, 'far off' — across a great distance. It carries the voice in telephone, the image in television, and feeling itself in telepathy.",
"soma":"Greek soma, 'body' — the physical frame set against the mind. It joins them in psychosomatic and names the chromosome, a 'coloured body' in the cell.",
"megas / megalo-":"Greek megas, 'great, large' (combining form megalo-) — vast in scale. It amplifies the megaphone, inflates the ego in megalomania, and piles up stone in the megalith.",
"pyr":"Greek pyr, 'fire' — flame itself. It lights the funeral pyre, the compulsion of pyromania, and the controlled fireworks of pyrotechnics.",
"dipsa":"Greek dipsa, 'thirst' — a craving to drink. Dipsomania is that craving turned to a helpless, driving need for drink.",
"biblion":"Greek biblion, 'book,' from Byblos, the port that shipped Egypt's papyrus — the material lent its name to the writing. The Book became the Bible, and bibliography is the listing of books.",
"mania":"Greek mania, 'madness, frenzy' — the mind seized and driven. It stands alone in the maniac and hangs as -mania on any obsession that runs away with a person.",
"a- / an-":"Greek a-, 'without' (an- before a vowel) — the plain negative. It empties belief in atheist, name in anonymous, and feeling in apathy.",
"tempus / tempor-":"Latin tempus, 'time' (stem tempor-) — the passing hour. It measures the temporary, the contemporary who shares your time, and the tempo that sets its pace.",
"ana-":"Greek ana-, 'up, back, again' — motion upward or in reverse. It runs backward in anachronism, loosens upward in analysis, and cuts up in anatomy.",
"syn-":"Greek syn-, 'with, together' — a bringing into one. It fuses parts in synthesis, matches sense in synonym, and locks clocks together in synchronize.",
"dia-":"Greek dia-, 'through, across' — passage from side to side. It cuts across in diameter, runs between speakers in dialogue, and sees through the case in diagnosis.",
"ex-":"Latin ex-, 'out' — motion outward. It leaves by the exit, pulls out in extract, and shuts out in exclude.",
"con-":"Latin con-, 'with, together' — a strengthened joining. It links in connect, runs alongside in concur, and breathes together in conspire.",
"similis":"Latin similis, 'like, resembling' — matched in form. It gives the similar, the simile that says one thing is like another, and verisimilitude, the mere look of truth.",
"fallere":"Latin fallere, 'to deceive, to trip' — to make a thing give way underfoot. From that stumble come false, the fallacy that trips up thought, and the infallible who never slip.",
"mendax":"Latin mendax, 'given to lying,' from mentiri, 'to lie' — a liar by habit, not accident. Mendacious keeps that settled dishonesty.",
"duo / duplex":"Latin duo, 'two,' and duplex, 'twofold' — a pair and its folding. It counts the duo, copies in duplicate, and, when the two faces turn false, becomes duplicity.",
"simulare":"Latin simulare, 'to make like,' from similis — to put on a likeness. To simulate is to feign a thing present, to dissimulate to feign it absent.",
"varicare":"Latin varicare, 'to straddle,' from varus, 'bent, bow-legged' — to walk with a crooked, spraddled gait. To prevaricate is to walk crookedly around the truth, dodging a straight answer.",
"species":"Latin species, 'a look, appearance,' from specere, 'to see' — how a thing shows to the eye. It gives the specious, fair to look at but false beneath, and the special, singled out by its look.",
"syn / sym":"Greek syn, 'with, together' (sym- before b, m, p) — a living or sounding as one. It shares a life in symbiosis, a feeling in sympathy, and a sound in symphony.",
"opsis":"Greek opsis, 'sight, view' — a look taken at a thing. It is the -opsy of biopsy and autopsy, the viewing of tissue, and the synopsis, a whole seen at one glance.",
"amphi-":"Greek amphi-, 'on both sides, around' — encompassing two at once. The amphibian lives both lives, water and land, and the amphitheatre seats the crowd all the way around.",
"mori / mort-":"Latin mori, 'to die,' with the stem mort-, 'death' — the end of life. It marks the mortal, the mortuary, and the moribund, already at death's door.",
"necros":"Greek nekros, 'corpse' — the dead body. It fills the necropolis, city of the dead, calls up the dead in necromancy, and names the tissue-death of necrosis.",
"polis":"Greek polis, 'city, city-state' — the self-governing town at the heart of Greek life. It swells into the metropolis, animates politics (the city's affairs), and even the police who keep its order.",
"manteia":"Greek manteia, 'prophecy,' from mantis, 'seer' — divination of what is hidden. It is the -mancy of necromancy, foretelling by the dead.",
"necare":"Latin necare, 'to kill' — to put to death. It hides in internecine, a slaughter shared on both sides, and pernicious, thoroughly deadly by slow degrees.",
"manus":"Latin manus, 'hand' — the hand at work. It labours in manual, writes the manuscript by hand, builds in manufacture, and, more slyly, manipulates.",
"capere":"Latin capere, 'to seize, take' — the grasping hand. It captures, makes capable (able to take hold), and, softened through the prefixes, lets us accept and receive.",
"dare / datum":"Latin dare, 'to give' (participle datum, 'a thing given') — an offering handed over. It gives us data, to donate, and even tradition, a handing-over of custom from age to age.",
"pes, pedis":"Latin pes, 'foot' (stem ped-) — the human foot. It works the pedal, walks in pedestrian, and shackles the feet in impede.",
"corpus, corporis":"Latin corpus, 'body' (stem corpor-) — the whole physical frame. It lies in the corpse, gathers many into one body in corporation, and takes a thing in bodily in incorporate.",
"caput, capitis":"Latin caput, 'head' (stem capit-) — the head that leads. It tops the capital city, names the captain who heads the ship, strikes the head off in decapitate, and counts per capita, 'by heads.'",
"léger":"French léger, 'light, nimble,' from Latin levis — light on the fingers. It survives in legerdemain, 'light of hand,' the conjurer's quick sleight.",
"animus / anima":"Latin animus, 'spirit, mind,' and anima, 'breath, soul' — the breath that is life. It animates the living, sours into animosity, lifts the soul in magnanimous, and unites all hearts in unanimous.",
"aequus":"Latin aequus, 'level, equal' — balanced, even. It makes things equal, holds the mind level in equanimity, splits the globe at the equator, and is enough in adequate.",
"pusillus":"Latin pusillus, 'very small, petty' — tiny in size and in spirit. Joined with animus, 'spirit,' it makes pusillanimous, small-souled and faint-hearted.",
"unus":"Latin unus, 'one' — single and whole. It counts the unit, binds many into one in unite, makes all hearts one in unanimous, and turns all things into a single universe.",
"advertere":"Latin advertere, ad- (toward) plus vertere (to turn) — to turn the mind toward. To advertise is to turn eyes toward a thing, and the adverse has turned against you.",
"vertere / versus":"Latin vertere, 'to turn' (participle versus) — turning as the master motion. It supplies the -version, -verse, and -vert of a hundred words, each a different way of turning.",
"vertigo":"Latin vertigo, 'a whirling,' from vertere, 'to turn' — the world spinning about you. It names vertigo itself and the vertiginous drop that sets the head reeling.",
"sub-":"Latin sub-, 'under, below' — beneath the surface. It dives in the submarine, undermines in subvert, and yields itself up in submit.",
"contra-":"Latin contra-, 'against, opposite' — set face to face. It speaks against in contradict, stands opposed in contrary, and pushes back in counter.",
"kallos":"Greek kallos, 'beauty' — grace to the eye. It writes beautifully in calligraphy and turns bright shifting patterns in the kaleidoscope, a 'viewer of beautiful forms.'",
"epi-":"Greek epi-, 'upon, over, after' — laid on top. It rests the epidermis upon the skin, cuts the epitaph on the stone, and closes the tale in the epilogue.",
"scribere / scriptus":"Latin scribere, 'to write' (participle scriptus) — letters set down. It runs the script, describes, writes ahead in prescribe, and copies across in transcript.",
"credere":"Latin credere, 'to believe, to trust' — to give faith to a thing. It extends credit, judges a story credible, and holds its articles of belief in a creed.",
"ad- / ac-":"Latin ad-, 'to, toward' (ac- before c) — motion up to a thing. It sticks in adhere, moves forward in advance, and takes toward oneself in accept.",
"onyma":"Greek onyma, an Aeolic form of onoma, 'name' — a thing's naming. It matches names in synonym, hides one in pseudonym, and strips it away in anonymous.",
"nomen, nominis":"Latin nomen, 'name' (stem nomin-) — the name a thing bears. It nominates, values a thing at its nominal face, and orders the world's names in nomenclature.",
"pseudes":"Greek pseudes, 'false, lying' — counterfeit. It masks the writer in pseudonym and stamps the sham in pseudo-science.",
"eu-":"Greek eu-, 'good, well' — a favourable turn. It softens the truth in euphemism, floods the mood in euphoria, and speaks well of the dead in eulogy.",
"dys-":"Greek dys-, 'bad, hard, faulty' — gone wrong. It breaks down in dysfunction, tangles reading in dyslexia, and sours the ideal city into a dystopia.",
"kakos":"Greek kakos, 'bad, ugly' — harsh and ill-made. It grates the ear in cacophony and cramps the hand in cacography, bad writing.",
"phone":"Greek phone, 'sound, voice' — the voice carried as sound. It travels in the telephone, sounds together in symphony, and studies speech-sound in phonetics.",
"pheme":"Greek pheme, 'speech, report,' from phanai, 'to speak' — what is said aloud about a thing. It is the -phemy of euphemism, kind speech, and blasphemy, speech against the sacred.",
"doxa":"Greek doxa, 'opinion, glory' — what is held or thought. It fixes right opinion in orthodox, sets thought against itself in paradox, and marks the dissenter as heterodox.",
"thanatos":"Greek thanatos, 'death,' personified as the gentle god who ends life — the fact of dying. It offers an easy death in euthanasia and studies death itself in thanatology.",
"specere / spectus":"Latin specere, 'to look' (participle spectus) — the directed gaze. It stages the spectacle, looks into a thing in inspect, and looks back in regard in respect.",
"per-":"Latin per-, 'through, thoroughly' — all the way across. It takes in through the senses in perceive, spreads through in pervade, and holds through to the end in persist.",
"circum-":"Latin circum-, 'around' — a full circuit. Circumspect looks around before it acts, circumvent gets around an obstacle, and circumscribe draws a line around a limit.",
"myein":"Greek myein, 'to shut the eyes or lips' — closing against the world. It narrows the sight in myopia, the eyes half-shut, and seals the lips on secrets in mystery.",
"presbys":"Greek presbys, 'old man, elder' — age with authority. It dims the aging eye in presbyopia and ordains the presbyter, the church elder who becomes our 'priest.'",
"caedere / -cida":"Latin caedere, 'to cut, to strike down,' with the agent form -cida, 'killer' — the fatal cut. It ends life in the -cide of homicide, opens flesh in incision, and, cut short and clean, makes the concise.",
"frater":"Latin frater, 'brother' — the brother by blood or bond. It warms the fraternal, gathers the fraternity, and turns deadly in fratricide.",
"rex, regis":"Latin rex, 'king' (stem reg-) — the ruler by right. It crowns the regal, kills the king in regicide, and marks the regnal years of a reign.",
"genos":"Greek genos, 'race, kind, birth' — a shared descent. It destroys a whole people in genocide, opens things in genesis, and traces the line in genealogy.",
"uxor":"Latin uxor, 'wife' — the married woman of the house. It survives almost only in uxorious, doting on one's wife past all measure.",
"gignere / genus":"Latin gignere, 'to beget,' and genus, 'birth, kind' — origin and the class it founds. It sorts the genus, brings forth in generate, is present from birth in congenital, and lives on in progeny.",
"puer":"Latin puer, 'boy, child' — the young and untried. It belittles the puerile, childish past its years, and names the puerperal fever of childbed.",
"senex":"Latin senex, 'old man' — age and its authority. It weakens in the senile, but rules in the senator and ranks first in the senior.",
"nostos":"Greek nostos, 'a return home' — the homecoming of Odysseus and his kind. Bound to algos, 'pain,' it aches for that return in nostalgia.",
"algos":"Greek algos, 'pain' — bodily or bittersweet ache. It stabs in neuralgia, longs in nostalgia, and is numbed by an analgesic.",
"sopor":"Latin sopor, 'deep sleep' — heavy, drugged slumber. A soporific brings it on, dulling the mind toward sleep.",
"hypnos":"Greek hypnos, 'sleep,' the god who closed men's eyes — natural or induced. Hypnosis is the sleeplike trance, and the hypnotic is what casts it.",
"dis-":"Latin dis-, 'apart, away, not' — a scattering and a denial. It flings apart in disperse, breaks from the view in dissent, and simply negates in disagree.",
"-escent":"Latin -escere, the ending that marks a beginning or a growing-into — a process just under way. It is convalescent (growing well), adolescent (growing up), and luminescent (beginning to glow).",
"pugnare":"Latin pugnare, 'to fight,' from pugnus, 'fist' — combat at close quarters. It squares up in pugnacious, recoils in repugnant, and attacks an argument in impugn.",
"pugnus / pugil":"Latin pugnus, 'fist,' and pugil, 'boxer' — the raised hand of a fighter. From pugil comes the pugilist, the boxer who fights with fists.",
"bellum":"Latin bellum, 'war' — armed conflict. It arms the belligerent and bellicose, kindles the rebel who wars again, and dates the antebellum world before the war.",
"gerere":"Latin gerere, 'to carry, to conduct, to wage' — to bear a thing or bear it out. It wages war in belligerent, carries meaning in gesture, and carries food through in digest.",
"sequi / secutus":"Latin sequi, 'to follow' (participle secutus) — coming after in train. It follows in the sequel, runs consecutive, pursues in prosecute, and lines up in sequence.",
"ob-":"Latin ob-, 'toward, against, in the way of' — set facing or blocking. It bars the path in obstruct, sets against in oppose, and lies square in your way in obvious.",
"im- / in-":"Latin in-, 'in, into, upon' (im- before b, m, p) — motion inward. It drives at in impugn, sets upon in impose, and carries in in import.",
"non":"Latin non, 'not' — flat negation. It cools the nonchalant into un-caring, empties meaning in nonsense, and refuses all description in nondescript.",
"-acious":"Latin -ax, -acis, 'given to, inclined to,' becoming English -acious — a habit turned to trait. It is the fighting streak in pugnacious, the grip of tenacious, and the daring of audacious.",
/* --- pieces split from the "A + B" compound roots, so each drills on its own --- */
"vox":"Latin vox, 'voice' — the sound of speech itself. It carries far in vociferous, votes aloud in 'vocal,' and is what a vowel gives a word.",
"ferre":"Latin ferre, 'to carry, to bear' — to bring a thing along. It carries the voice in vociferous, bears fruit in fertile, and moves a whole word in transfer.",
"magnus":"Latin magnus, 'great, large' — grand in size or soul. It magnifies, opens the great hall of a magnate, and lends its greatness to the magnanimous.",
"animus":"Latin animus, 'spirit, mind, courage' — the breath that drives a person. It rouses animosity when soured and lifts the soul in magnanimous and pusillanimous.",
"demos":"Greek demos, 'the people, the common folk' — the citizen body. It rules in democracy, is swayed in the demagogue, and is counted in demography.",
"agogos":"Greek agogos, 'leader,' from agein, 'to lead' — one who draws others along. It leads the crowd in demagogue and trains the young in pedagogue.",
"sykon":"Greek sykon, 'fig' — the sweet fruit of Attica. It survives, oddly, in sycophant, the flatterer once mocked as a 'fig-shower,' an informer against fig-smugglers.",
"phainein":"Greek phainein, 'to show, to bring to light' — to make a thing appear. It shows figs in sycophant, shows the self in the phenomenon, and lights up phosphorus, the 'light-bearer.'",
"eikon":"Greek eikon, 'image, likeness' — a figure that stands for another. It is the sacred icon, and the one who smashes it is the iconoclast.",
"klaein":"Greek klaein, 'to break' — to shatter. It breaks images in iconoclast, the idol-breaker who turns from statues to break with received belief."
};
