import type { StringMap } from "../types/content";

export const ETYM = {
  "ego": "Latin for 'I', the ordinary first-person pronoun; Freud later borrowed it for the conscious self.",
  "alter": "Latin 'the other (of two)'; gives us alternate, alter ego, and altruism.",
  "verto / versus": "Latin vertere 'to turn'; its past participle versus underlies convert, reverse, and version.",
  "intro-": "Latin adverb 'to the inside'; the inward-facing prefix in introvert and introduce.",
  "extra-": "Latin 'outside, beyond'; the outward prefix in extrovert, extraordinary, and external.",
  "ambi-": "Latin 'both, around'; the ambidextrous use both hands, the ambivalent feel both ways.",
  "misein": "Greek 'to hate'; the mis- of misanthrope and misogyny.",
  "anthropos": "Greek 'human being'; anthropology studies it, the misanthrope hates it.",
  "asketes": "Greek 'one who trains', from askein 'to exercise'; the ascetic disciplines the body.",
  "internus": "Latin 'inward', from inter 'between'; internal and internist descend from it.",
  "obstetrix": "Latin 'one who stands before (the birth)', from ob- + stare; source of obstetrics.",
  "pais, paidos": "Greek 'child'; the ped- of pediatrics and the -pedia of encyclopedia.",
  "derma": "Greek 'skin'; dermatology and epidermis keep it.",
  "ophthalmos": "Greek 'eye'; the ophthalmologist treats it.",
  "orthos": "Greek 'straight, correct'; orthodox belief and orthopedics both aim to straighten.",
  "kardia": "Greek 'heart'; cardiac and cardiology come from it.",
  "neuron": "Greek 'sinew, nerve'; neurology and the neuron itself.",
  "psyche": "Greek 'breath, soul', personified as a maiden; psychology and psyche.",
  "iatreia": "Greek 'healing', from iatros 'physician'; the -iatry of psychiatry and podiatry.",
  "odontos": "Greek 'tooth'; orthodontist and mastodon (named for its teeth) share it.",
  "opsis / optikos": "Greek 'sight'; optic, optometry, and autopsy (a seeing for oneself).",
  "metron": "Greek 'measure'; metre, thermometer, and geometry.",
  "osteon": "Greek 'bone'; osteopath and osteoporosis.",
  "cheir": "Greek 'hand'; the chiropractor and chiropodist both work by hand.",
  "pous, podos": "Greek 'foot'; podiatry, tripod, and octopus (eight-foot).",
  "graphein": "Greek 'to scratch, write'; graph, biography, and photograph.",
  "geron": "Greek 'old man'; gerontology and geriatric.",
  "analyein": "Greek 'to loosen up', ana- 'up' + lyein 'to loosen'; source of analysis.",
  "astron": "Greek 'star'; astronomy, astronaut, and disaster (a 'bad star').",
  "nomos": "Greek 'law, custom', from nemein 'to distribute'; the -nomy of astronomy and economy.",
  "ge": "Greek 'earth' (the goddess Gaia); geography, geology, geometry.",
  "bios": "Greek 'life'; biology, biography, antibiotic.",
  "botane": "Greek 'pasture, herb', from boskein 'to feed'; source of botany.",
  "zoion": "Greek 'living creature'; zoo, zoology, protozoa.",
  "entomon": "Greek 'notched (creature)', for the insect's segmented body; source of entomology.",
  "etymon": "Greek 'the true sense of a word'; the origin of etymology itself.",
  "socius": "Latin 'ally, companion'; society, social, associate.",
  "logos": "Greek 'word, reason, account'; the -logy ending and the word logic.",
  "noscere / notus": "Latin 'to get to know'; notorious, notice, and note.",
  "summa": "Latin 'highest, topmost'; summit, sum, and summary.",
  "corrigere": "Latin com- + regere 'to straighten out'; correct and incorrigible.",
  "vetus": "Latin 'old'; veteran and inveterate (grown old in a habit).",
  "genitus": "Latin, past participle of gignere 'to beget'; congenital and genitive.",
  "chronos": "Greek 'time' (the god Chronos); chronic, chronology, synchronize.",
  "pathos": "Greek 'suffering, feeling'; pathology, sympathy, and the many -path words.",
  "scire": "Latin 'to know'; science, conscience, and prescient.",
  "grex, gregis": "Latin 'flock, herd'; gregarious, congregation, segregate.",
  "par": "Latin 'equal'; par, parity, compare, disparage.",
  "aequus + vox": "Latin aequus 'equal' + vox 'voice' — to speak on both sides at once: equivocate.",
  "placare": "Latin 'to calm, appease'; placate, placid, and implacable.",
  "scribere": "Latin 'to write'; scribe, describe, manuscript.",
  "via": "Latin 'road, way'; via, deviate (off the road), obvious (in the way).",
  "miles, militis": "Latin 'soldier'; military and militant.",
  "malus": "Latin 'bad, evil'; malice, malady, malign.",
  "condonare": "Latin com- + donare 'to give up (a claim)'; the source of condone.",
  "adulari": "Latin 'to fawn like a dog'; gives us adulation.",
  "vacillare": "Latin 'to sway, totter'; source of vacillate.",
  "tacere": "Latin 'to be silent'; tacit and taciturn.",
  "Lakonia": "The region of Sparta, whose people were famed for terse speech; hence laconic.",
  "garrire": "Latin 'to chatter'; source of garrulous.",
  "volvere": "Latin 'to roll, turn'; revolve, volume, and voluble (rolling on in talk).",
  "verbum": "Latin 'word'; verb, verbal, verbatim, verbose.",
  "cogere": "Latin com- + agere 'to drive together'; cogent and cogency.",
  "vox + ferre": "Latin vox 'voice' + ferre 'to carry' — a carrying voice: vociferous.",
  "sententia": "Latin 'opinion, judgment', from sentire 'to feel'; sentence and sententious.",
  "tergere": "Latin 'to wipe'; the -terge of detergent, and terse (wiped clean, polished).",
  "Martinet": "From Jean Martinet, Louis XIV's strict drillmaster; his name became the word.",
  "sykon + phainein": "Greek sykon 'fig' + phainein 'to show' — an informer's old gesture: sycophant.",
  "dilettare": "Italian 'to delight', from Latin delectare; a dilettante dabbles for pleasure.",
  "vir": "Latin 'man, hero'; virile, virtue, and triumvirate.",
  "Chauvin": "From Nicolas Chauvin, a fanatically devoted soldier of Napoleon; hence chauvinism.",
  "eikon + klaein": "Greek eikon 'image' + klaein 'to break' — an iconoclast smashes idols.",
  "hypochondria": "Greek 'the soft parts below the ribs', once thought the seat of melancholy.",
  "ciarlare": "Italian 'to chatter'; source of charlatan, the babbling quack.",
  "Philistine": "The biblical enemies of Israel; later, anyone hostile or indifferent to culture.",
  "monos + mania": "Greek monos 'one' + mania 'madness' — a single fixed obsession: monomania.",
  "vivere": "Latin 'to live'; vivid, survive, vivacious.",
  "fatigare": "Latin 'to weary'; fatigue and indefatigable (untiring).",
  "ingenuus": "Latin 'native, freeborn', hence frank and honest; source of ingenuous.",
  "magnus + animus": "Latin magnus 'great' + animus 'spirit' — greatness of soul: magnanimous.",
  "vertere": "Latin 'to turn'; convert, versatile, adversity.",
  "Stoa": "The painted porch (stoa) in Athens where Zeno taught; hence stoic.",
  "trepidus": "Latin 'agitated, alarmed'; trepidation and intrepid (not alarmed).",
  "scintilla": "Latin 'spark'; scintillate and scintillating wit.",
  "urbs": "Latin 'city'; urban, suburb, and urbane (polished by city life).",
  "gamos": "Greek 'marriage'; monogamy, polygamy, bigamy.",
  "monos": "Greek 'single, alone'; monopoly, monologue, monotony.",
  "bi-": "Latin 'two, twice'; bicycle, bilingual, biennial.",
  "polys": "Greek 'many'; polygon, polyglot, polygamy.",
  "aner, andros": "Greek 'man, male'; android, misandry, polyandry.",
  "agora": "Greek 'assembly, marketplace'; agoraphobia is the fear of open public spaces.",
  "claustrum": "Latin 'a lock, enclosure'; cloister and claustrophobia.",
  "xenos": "Greek 'stranger, guest'; xenophobia and the gas xenon.",
  "akros": "Greek 'topmost'; acrobat (walking high), acropolis, acrophobia.",
  "kleptein": "Greek 'to steal'; kleptomania and kleptocracy.",
  "kratos / -cracy": "Greek 'strength, rule'; the -cracy of democracy and aristocracy.",
  "archein / -archy": "Greek 'to rule, be first'; monarchy, anarchy, and the arch- of archbishop.",
  "autos": "Greek 'self'; automatic, autonomy, autograph.",
  "oligos": "Greek 'few'; oligarchy is rule by the few.",
  "ploutos": "Greek 'wealth' (the god Plutus); plutocracy is rule by the rich.",
  "theos": "Greek 'god'; theology, atheist, monotheism.",
  "mater": "Latin 'mother'; maternal, matron, matriarchy, matrix.",
  "pater": "Latin 'father'; paternal, patriarch, patriot.",
  "hieros": "Greek 'holy, sacred'; hierarchy ('rule of the sacred') and hieroglyph.",
  "demos + agogos": "Greek demos 'people' + agogos 'leader' — the demagogue leads the mob.",
  "loqui / locutus": "Latin 'to speak'; eloquent, loquacious, circumlocution.",
  "dicere / dictus": "Latin 'to say'; dictate, verdict, contradict.",
  "solus": "Latin 'alone'; solo, solitary, soliloquy.",
  "circum": "Latin 'around'; circle, circumference, circumnavigate.",
  "grandis": "Latin 'full-grown, great'; grand, grandiose, aggrandize.",
  "e / ex": "Latin 'out of'; exit, emit, evoke.",
  "bene": "Latin 'well, good'; benefit, benevolent, benediction.",
  "male": "Latin 'badly'; malediction, malevolent, malfunction.",
  "com / col": "Latin 'with, together'; combine, collect, collaborate.",
  "jus, juris": "Latin 'law, right'; justice, jury, jurisdiction.",
  "judex, judicis": "Latin jus 'law' + dicere 'to say' — the judge; source of judicial and prejudice.",
  "lis, litis": "Latin 'lawsuit, dispute'; litigate and litigious.",
  "jurare": "Latin 'to swear an oath'; jury, perjury, abjure.",
  "verus": "Latin 'true'; verify, verdict, veracity.",
  "culpa": "Latin 'fault, blame'; culprit, culpable, exculpate (to clear of blame).",
  "crimen": "Latin 'charge, accusation'; crime, incriminate, recriminate.",
  "prudentia": "Latin, contracted from providentia 'foresight'; prudent and jurisprudence.",
  "dikē": "Greek 'justice, right'; the -dicy of theodicy.",
  "in-": "Latin 'in, into, against'; invade and incur — and the negating in- of invalid.",
  "tele-": "Greek 'far off'; telephone, television, telepathy.",
  "soma": "Greek 'body'; psychosomatic and chromosome.",
  "megas / megalo-": "Greek 'great, large'; megaphone, megalomania, megalith.",
  "pyr": "Greek 'fire'; pyre, pyromania, pyrotechnics.",
  "dipsa": "Greek 'thirst'; dipsomania is a craving for drink.",
  "biblion": "Greek 'book' (from Byblos, source of papyrus); Bible and bibliography.",
  "mania": "Greek 'madness, frenzy'; maniac and the -mania suffix.",
  "a- / an-": "Greek negating prefix 'without'; atheist, anonymous, apathy.",
  "tempus / tempor-": "Latin 'time'; temporary, contemporary, tempo.",
  "ana-": "Greek 'up, back, again'; anachronism, analysis, anatomy.",
  "syn-": "Greek 'with, together'; synthesis, synonym, synchronize.",
  "dia-": "Greek 'through, across'; diameter, dialogue, diagnosis.",
  "ex-": "Latin 'out'; exit, extract, exclude.",
  "con-": "Latin 'with, together'; connect, concur, conspire.",
  "similis": "Latin 'like'; similar, simile, assimilate, verisimilitude.",
  "fallere": "Latin 'to deceive'; false, fallacy, infallible.",
  "mendax": "Latin 'given to lying', from mentiri; source of mendacious.",
  "duo / duplex": "Latin 'two / twofold'; duo, duplicate, duplicity, double.",
  "simulare": "Latin 'to make like', from similis; simulate and dissimulate.",
  "varicare": "Latin 'to straddle', from varus 'bent'; source of prevaricate (to walk crookedly).",
  "species": "Latin 'a look, appearance', from specere 'to see'; specious and special.",
  "syn / sym": "Greek 'with, together'; symbiosis, sympathy, symphony.",
  "opsis": "Greek 'sight, view'; the -opsy of biopsy and autopsy, and synopsis.",
  "amphi-": "Greek 'on both sides'; amphibian (both lives) and amphitheatre.",
  "mori / mort-": "Latin 'death, to die'; mortal, mortuary, immortal, moribund.",
  "necros": "Greek 'corpse'; necropolis, necromancy, necrosis.",
  "polis": "Greek 'city, city-state'; metropolis, politics, police.",
  "manteia": "Greek 'prophecy', from mantis 'seer'; the -mancy of necromancy.",
  "necare": "Latin 'to kill'; internecine and pernicious descend from it.",
  "manus": "Latin 'hand'; manual, manuscript, manufacture, manipulate.",
  "capere": "Latin 'to seize, take'; capture, capable, accept, receive.",
  "dare / datum": "Latin 'to give'; data, donate, tradition (a handing over).",
  "pes, pedis": "Latin 'foot'; pedal, pedestrian, impede (to shackle the feet).",
  "corpus, corporis": "Latin 'body'; corpse, corporation, corporal, incorporate.",
  "caput, capitis": "Latin 'head'; capital, captain, decapitate, per capita.",
  "léger": "French 'light, nimble', from Latin levis; source of legerdemain (sleight of hand).",
  "animus / anima": "Latin 'breath, soul'; animate, animosity, magnanimous, unanimous.",
  "aequus": "Latin 'level, equal'; equal, equanimity, equator, adequate.",
  "pusillus": "Latin 'very small'; with animus 'spirit' it makes pusillanimous (faint-hearted).",
  "unus": "Latin 'one'; unit, unite, unanimous, universe.",
  "advertere": "Latin ad- + vertere 'to turn toward'; advertise, advert, and adverse.",
  "vertere / versus": "Latin 'to turn'; the version, -verse, and -vert of countless words.",
  "vertigo": "Latin 'a whirling', from vertere 'to turn'; source of vertigo and vertiginous.",
  "sub-": "Latin 'under, below'; submarine, subvert, submit.",
  "contra-": "Latin 'against'; contradict, contrary, counter.",
  "kallos": "Greek 'beauty'; calligraphy (beautiful writing) and kaleidoscope.",
  "epi-": "Greek 'upon, over'; epidermis, epitaph, epilogue, epidemic.",
  "scribere / scriptus": "Latin 'to write'; script, describe, prescribe, transcript.",
  "credere": "Latin 'to believe, trust'; credit, credible, incredible, creed.",
  "ad- / ac-": "Latin 'to, toward'; adhere, advance, accept, address.",
  "onyma": "Greek (Aeolic) 'name'; synonym, pseudonym, anonymous.",
  "nomen, nominis": "Latin 'name'; nominate, nominal, nomenclature, noun.",
  "pseudes": "Greek 'false, lying'; pseudonym and pseudo-science.",
  "eu-": "Greek 'good, well'; euphemism, euphoria, eulogy, euphony.",
  "dys-": "Greek 'bad, difficult'; dysfunction, dyslexia, dystopia.",
  "kakos": "Greek 'bad'; cacophony (harsh sound) and cacography.",
  "phone": "Greek 'sound, voice'; telephone, symphony, phonetics.",
  "pheme": "Greek 'speech, report', from phanai 'to speak'; the -phemy of euphemism and blasphemy.",
  "doxa": "Greek 'opinion, glory'; orthodox, paradox, heterodox.",
  "thanatos": "Greek 'death' (the god Thanatos); euthanasia and thanatology.",
  "specere / spectus": "Latin 'to look'; spectacle, inspect, respect, spectator.",
  "per-": "Latin 'through, thoroughly'; perceive, pervade, persist.",
  "circum-": "Latin 'around'; circumspect (looking around), circumvent, circumscribe.",
  "myein": "Greek 'to shut (the eyes)'; source of myopia (near-sight) and mystery.",
  "presbys": "Greek 'old man, elder'; presbyopia (aging sight) and presbyter (priest).",
  "caedere / -cida": "Latin 'to cut, kill'; the -cide of homicide, and incision and concise.",
  "frater": "Latin 'brother'; fraternal, fraternity, fratricide.",
  "rex, regis": "Latin 'king'; regal, regicide, and the reg- of regnal.",
  "genos": "Greek 'race, kind, birth'; genocide, genesis, genealogy.",
  "uxor": "Latin 'wife'; uxorious (excessively fond of one's wife).",
  "gignere / genus": "Latin 'to beget; birth, kind'; genus, generate, congenital, progeny.",
  "puer": "Latin 'boy, child'; puerile and puerperal.",
  "senex": "Latin 'old man'; senile, senator, senior.",
  "nostos": "Greek 'return home'; with algos 'pain' it forms nostalgia.",
  "algos": "Greek 'pain'; neuralgia, nostalgia, analgesic.",
  "sopor": "Latin 'deep sleep'; soporific and sopor.",
  "hypnos": "Greek 'sleep' (the god Hypnos); hypnosis and hypnotic.",
  "dis-": "Latin 'apart, away, not'; disperse, dissent, disagree.",
  "-escent": "Latin -escere, marking a beginning; convalescent, adolescent, luminescent.",
  "pugnare": "Latin 'to fight'; pugnacious, repugnant, impugn.",
  "pugnus / pugil": "Latin pugnus 'fist' / pugil 'boxer'; source of pugilist.",
  "bellum": "Latin 'war'; belligerent, bellicose, rebel, antebellum.",
  "gerere": "Latin 'to carry, conduct, wage'; belligerent, gesture, digest.",
  "sequi / secutus": "Latin 'to follow'; sequel, consecutive, prosecute, sequence.",
  "ob-": "Latin 'toward, against'; obstruct, oppose, obvious.",
  "im- / in-": "Latin 'in, into, upon' (im- before b, m, p); impugn, impose, import.",
  "non": "Latin 'not'; nonchalant, nonsense, nondescript.",
  "-acious": "Latin -ax, -acis 'given to'; pugnacious, tenacious, audacious.",
  "oculus": "Latin 'eye'; source of oculist, ocular, and binocular.",
  "philo": "Greek philos 'loving'; the first element in philology and philanthropy.",
  "phile": "Greek philein 'to love'; the ending in bibliophile and xenophile.",
  "harmonia / harmonic": "Greek harmonia 'joining, concord'; source of harmony and philharmonic.",
  "sophia / sophos": "Greek sophia 'wisdom' and sophos 'wise'; philosophy and sophist preserve them.",
  "gyne": "Greek gyne 'woman'; gynecology and misogyny preserve the root.",
  "ateleia": "Greek ateleia 'tax exemption'; the source of philately.",
  "istry": "Greek -istria, denoting practice or occupation; seen in sophistry.",
  "fid / fidel": "Latin fides 'faith, trust'; fidelity, confide, perfidy, and infidel.",
  "titill": "Latin titillare 'to tickle'; source of titillate.",
  "tyro": "Latin tiro 'recruit, beginner'; source of tyro.",
  "centr": "Latin centrum, from Greek kentron 'center, sharp point'; eccentric and concentric.",
  "per": "Latin per, 'away, through'; the intensifying prefix in perfidy and perjury.",
  "vol": "Latin velle 'to wish'; benevolent and malevolent are literally wishing well or ill.",
  "moric": "Greek moros 'foolish'; source of sophomoric.",
  "simul": "Latin simulare 'to make like'; simulate and dissimulate.",
  "atim": "Latin -atim 'by, in order'; verbatim is word for word.",
  "ambul": "Latin ambulare 'to walk'; amble, ambulance, and somnambulist.",
  "omni": "Latin omnis 'all'; omniscient, omnipotent, and omnivore.",
  "vor": "Latin vorare 'to devour'; voracious and carnivorous.",
  "carni": "Latin caro, carnis 'flesh'; carnal and carnivorous.",
  "potent": "Latin potens 'powerful'; potent, omnipotent, and potential.",
  "somn": "Latin somnus 'sleep'; insomnia and somnambulist.",
  "gauche": "French gauche 'left'; its social sense grew from the left hand's old association with clumsiness.",
  "sinister": "Latin sinister 'left'; Roman augury gave it the later sense of ominous.",
  "acious": "Latin -ax, -acis, 'inclined to'; the ending in vivacious and loquacious.",
  "droit": "French droit 'right'; the counterpart of gauche, 'left'.",
  "Anglo": "Latin Anglus 'English'; source of Anglophile.",
  "celib": "Latin caelebs 'unmarried'; source of celibate and celibacy.",
  "pro": "Greek pro 'before'; prognosis is knowledge beforehand.",
  "aristo": "Greek aristos 'best'; aristocracy is rule by the best.",
  "pan": "Greek pan, pantos 'all'; pandemic and panorama.",
  "ventri": "Latin venter 'belly'; ventriloquist originally speaks from the belly.",
  "cosmo": "Greek kosmos 'order, world'; cosmopolitan and microcosm.",
  "polit": "Greek polites 'citizen'; politics and cosmopolitan.",
  "phobia": "Greek phobos 'fear, panic'; xenophobia and necrophobia.",
  "uni": "Latin unus 'one'; univocal, unit, and universe.",
  "taph": "Greek taphos 'tomb'; epitaph and cenotaph."
} satisfies StringMap;
